# Generated by Django 3.0.6 on 2020-05-07 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=30)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('twitter_handle', models.CharField(blank=True, max_length=15)),
                ('instagram_handle', models.CharField(blank=True, max_length=30)),
                ('fb_page', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('genre', models.CharField(blank=True, max_length=30)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
    ]
