# Generated by Django 3.0.6 on 2020-05-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scroller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicvideo',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/%Y/%m/%d/'),
        ),
    ]
